spring.application.name=login
server.port = 8080

spring.datasource.url = jdbc:mysql://localhost:3306/login
spring.datasource.username = root
spring.datasource.password = 
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql = true


#Clave secreta 
application.security.jwt.secret-key = 839283cndnnc323555kjkkkkcddeq323K34KLKOK434CR7jajdjasndaskldmasñlde232345678mcmmasmdmsdmsad

#Equivale 24 horas antes de expirar
application.security.jwt.expiration = 86400000 

#Ignoro eureka por el momento
eureka.client.enabled=false
eureka.client.register-with-eureka=false
