spring.application.name=login
server.port = 8080

#Clave secreta 
application.security.jwt.secret-key = 839283cndnnc323555kjkkkkcddeq323K34KLKOK434CR7jajdjasndaskldmasñlde232345678mcmmasmdmsdmsad

#Equivale 24 horas antes de expirar
application.security.jwt.expiration = 86400000 

